### ISSUE TITLE
As a visitor, I want to see all the products on the product page so I can see al the available options

### ISSUE THREAD

**Issue by codaboba** [silvertigers/maskot#34]
As a visitor, I want to see all the products on the product page so I can see all the available options

**Comment by CBoetto** [comment]
Implementation:
We want to have a list of all our products stored in an Array in our Redux store.  Each product will have a 'category' key with a value that is equal to an array with a list of all categories for that product.  In our ProductList component's render method, we will filter through the entire catalog of products stored in that array in our store and find the ones that match the user's selected categories.  We will then map through that new array, plug the data of each product into a ProductThumbnail component, and make a <ul> of those products.
