### ISSUE TITLE
As an admin, I want to add, edit, (and delete) products so I can update what visitors see

### ISSUE THREAD

**Issue by codaboba** [silvertigers/maskot#7]
As an admin, I want to add, edit, (and delete) products so I can update what visitors see

**Comment by parigu2** [comment]
If the user is login as "admin", server check the log-in user is "isAdmin", show up a hidden button on the navigation bar which calls "Dashboard".  The dashboard make able to allow to show edit button of each products (Also, history of all of the orders, user information as well later).  An Express route on the backend, get all the current products list (GET, /api/products) and edit (POST /api/products & PUT/DELETE /api/products/:id).
